name:                tcp-messenger
version:             0.1.0.0
github:              "githubuser/tcp-messenger"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tcp-messenger#readme>

dependencies:
- base >= 4.7 && < 5
- socket == 0.8.3.0
- bytestring == 0.11.5.3
- network == 3.1.4.0
- unix-time == 0.4.11
- effectful == 2.2.2.0
- cereal == 0.5.8.3
- text == 2.0.2
- stm == 2.5.1.0
- hashtables == 1.3.1
# - hashable == 1.4.3.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-full-laziness

library:
  source-dirs: src

executables:
  tcp-messenger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tcp-messenger

tests:
  tcp-messenger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tcp-messenger
    - QuickCheck == 2.14.3
    - hspec == 2.10.10
    - quickcheck-instances == 0.3.30
